spring.jpa:
  show-sql: true
  hibernate.ddl=auto: create-drop

spring.datasource:
  platform: h2
  url: jdbc:h2:mem:currency-convertor-app

spring.h2.console.enabled: true

ratesInput:
  filepath: ${INPUT_FILE_PATH}
